#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
app.admin.username=${APP_ADMIN_USERNAME:admin}
app.admin.password=${APP_ADMIN_PASSWORD:admin123}
app.client-origin=${APP_CLIENT_ORIGIN:http://localhost:4200}
server.forward-headers-strategy=framework


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect